### ISSUE TITLE
Empty compare image being generated

### ISSUE THREAD

**Issue by mattgolding** [lukeapage/pngjs#91]
I have the following code which is generating an empty file to show the differences.  The file is created on the file system but it is 0kb.  The pixel diff count is showing 2500 so that all apears to be working.  Am i using the API wrong?

```
  const newFileData = fs.readFileSync(newFilePath);
  const newFilePng = PNG.sync.read(newFileData);

  const baselineFileData = fs.readFileSync(baselineFilePath);
  const baselineFilePng = PNG.sync.read(baselineFileData);

  let diffPng = new PNG({ width: newFilePng.width, height: newFilePng.height });
  const pixelDiff = pixelmatch(baselineFilePng.data, newFilePng.data, diffPng.data, newFilePng.width, newFilePng.height, { threshold: 0.0 });

  if (pixelDiff > 0) {
    console.log(clc.redBright('[ERR]') + ' - Different by: %d', pixelDiff);

    diffPng.pack().pipe(fs.createWriteStream(diffFilePath));
  }
```

Apologies is this is not the correct way to use issues.

**Comment by xkisu** [comment]
Do you mean the diffPng output is 0kb? That makes perfect sense and your using it right :) 

To put it simply, the size of the PNG will vary depending on how many pixels are colored within it. Since it's completely transparent there is very little data (roughly around 500 bytes) so it wouldn't show up on a kb scale.
